### PR TITLE
should not fail when no version in python_cluster_paths

### PR DESCRIPTION
**Pull request by faucct**

### CODE REVIEW

**Review by alextokarew — CHANGES_REQUESTED** [review]
How do you ensure that you have an appropriate Python version on the cluster and which one to use for running cluster parts of the job?

**Comment by faucct** [comment]
> How do you ensure that you have an appropriate Python version on the cluster

I assume that the cluster has the matching version and the UDFs will crash if it doesn't.

> which one to use for running cluster parts of the job?

I am not sure if I understood the question, but my code uses different python executables based on the supplied version.

**Comment by alextokarew** [comment]
I've checked it on out cluster an it seem to work, so the idea to get rid of `` sounds reasonable. But you also need to do modifications in these parts of the project:

Write a compat comment for `not os_release` block that it is preserved for backward compatibility and is subject to remove
https://github.com/ytsaurus/ytsaurus-spyt/blob/main/tools/release/publisher/config_generator.py#L147

The else clause can be safely removed, but check your clusters, maybe they also using old spyt version, in this case it also should be preserved and marked with comment
https://github.com/ytsaurus/ytsaurus-spyt/blob/main/tools/release/publisher/config_generator.py#L159

Remove all `python_cluster_paths` related code in YTsaurusOperationManager starting from here:
https://github.com/ytsaurus/ytsaurus-spyt/blob/main/resource-manager/src/main/scala/org/apache/spark/scheduler/cluster/ytsaurus/YTsaurusOperationManager.scala#L340

The tests should also be modified:
https://github.com/ytsaurus/ytsaurus-spyt/blob/main/e2e-test/common/cypress.py#L31

And this legacy atavism should also be removed
https://github.com/ytsaurus/ytsaurus-spyt/blob/main/yt-publish-plugin/src/main/scala/YsonableConfig.scala#L53

**Review by alextokarew — APPROVED** [review]

**Comment by alextokarew** [comment]
This PR https://github.com/ytsaurus/ytsaurus-spyt/pull/44 was successfully merged so we can close this one

**Comment by faucct** [comment]
It is another one that should be closed.

**Pull request closed without merging**
